# Generated by Django 4.1.1 on 2022-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["name"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="estimate",
            options={"ordering": ["modified_date", "id"]},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["modified_date", "id"]},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["label"],
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.AlterModelOptions(
            name="saler",
            options={
                "ordering": ["name"],
                "verbose_name": "Saler",
                "verbose_name_plural": "Salers",
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="estimate_saler_number",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="invoice saler number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_saler_number",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="invoice saler number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saler",
            name="estimate_number",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="estimate number"
            ),
        ),
        migrations.AddField(
            model_name="saler",
            name="invoice_number",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="invoice number"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(max_length=15, verbose_name="postal_code"),
        ),
        migrations.AlterField(
            model_name="saler",
            name="postal_code",
            field=models.CharField(max_length=15, verbose_name="postal_code"),
        ),
    ]
