# Generated by Django 4.1.1 on 2022-12-02 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales",
            "0002_alter_customer_options_alter_estimate_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="saler",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="saler/logo/",
                verbose_name="logo",
            ),
        ),
    ]
